# Generated by Django 5.1.1 on 2025-06-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_driverprofile_license_number_studentprofile_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='routes',
            field=models.ManyToManyField(blank=True, to='authentication.busroute'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='routes',
            field=models.ManyToManyField(blank=True, to='authentication.busroute'),
        ),
    ]
