# Generated by Django 5.1.1 on 2025-06-26 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_driverprofile_routes_studentprofile_routes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busroute',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='busroute',
            name='students',
        ),
        migrations.AlterField(
            model_name='busroute',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.driverprofile'),
        ),
    ]
