# Generated by Django 5.1.1 on 2025-06-28 11:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_busroute_created_at_remove_busroute_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroute',
            name='students',
            field=models.ManyToManyField(related_name='bus_routes', to=settings.AUTH_USER_MODEL),
        ),
    ]
